# Fecha: Agosto 12 del 2025
# Autor: David Beltran Gomez
# Materia: Sistemas Operativos
# Makefile: Automatiza instrucciones de compilación

GCC = gcc

matrices_BeltranGomez: matrices_BeltranGomez.c modulo.c modulo.h
        $(GCC) matrices_BeltranGomez.c modulo.c -o matrices_BeltranGomez

clean:
        rm -f *.o matrices_BeltranGomez