#########################################################################
#  Fecha: Agosto 12 del 2025                                            #
#  Autor: David Beltran Gomez                                           #
#  Materia: Sistemas Operativos                                         #
#  Makefile: Bash para automatizar instrucciones de compilacion         #
#  Se requiere automatizar la compilacion                               #
#########################################################################
#Comando para invocar el compilador de C
GCC = gcc
BIBLIOTECAS =
MODULOS =

PROGRAMAS = generalMM

all: $(PROGRAMAS)

principal:
        $(GCC) $(MODULO) $@.c -o $@