############################################
#		Pontificia Universidad Javeriana
# Autor: David Esteban Beltrán Gómez
# Materia: Sistemas Operativos
# Fichero: Automaticación Compilación
############################################

GCC = gcc
FLAGS = -fopenmp -lm

PROGRAMAS = Challenge1 Challenge2

Challenge1:
	$(GCC) $@.c -o $@ $(FLAGS)

Challenge2:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)