GCC = gcc
FLAGS =

PROGRAMAS = Challenge1 Challenge2 Challenge3 Challenge4 Challenge5 Challenge6 Challenge7 Challenge8 Challenge9

all: $(PROGRAMAS)

%: %.c
	$(GCC) $(FLAGS) $< -o $@

Challenge1:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge2:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge3:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge4:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge5:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge6:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge7:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge8:
	$(GCC) $(FLAGS) $@.c -o $@

Challenge9:
	$(GCC) $(FLAGS) $@.c -o $@

clean:
	rm -f $(PROGRAMAS)
