############################################
#		Pontificia Universidad Javeriana
# Autor: David Esteban Beltrán Gómez
# Materia: Sistemas Operativos
# Fichero: Automaticación Compilación
############################################

GCC = gcc
FLAGS = -fopenmp -lm

PROGRAMAS = Challenge1 Challenge2 Challenge3 Challenge4 Challenge5

Challenge1:
	$(GCC) $@.c -o $@ $(FLAGS)

Challenge2:
	$(GCC) $@.c -o $@ $(FLAGS)

Challenge3:
	$(GCC) $@.c -o $@ $(FLAGS)

Challenge4:
	$(GCC) $@.c -o $@ $(FLAGS)

Challenge5:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)